### ISSUE TITLE
Update to newest version of rollbar?

### ISSUE THREAD

**Issue by rgwozdz** [Ideame/winston-rollbar#3]
The winston-rollbar uses rollbar 0.3.2, but rollbar now up to 0.4.4.  As a result I am having this issue:
https://github.com/rollbar/node_rollbar/issues/21
Can u update the package.json to use 0.4.4?

**Comment by jpgarcia** [comment]
Sorry for the delayed answer! I was completely out. Just merged a PR which upgrades it to 0.5.6
